apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-vertx
  namespace: jfall-workshop
spec:
  template:
    metadata:
      name: helloworld-vertx-v1
    spec:
       containers:
         - image: docker.io/mgrygles/jfall2020
           env:
             - name: TARGET
               value: "Eclipse Vert.x helloworld JFall2020 Friends"

